"""Add report_generated column to time_block table

Revision ID: 4baabf606045
Revises: b27dc243174e
Create Date: 2025-05-20 20:51:20.401976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4baabf606045'
down_revision = 'b27dc243174e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_block', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_generated', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_block', schema=None) as batch_op:
        batch_op.drop_column('report_generated')

    # ### end Alembic commands ###
